name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            set -euo pipefail

            cd "${{ secrets.DEPLOY_PATH }}"

            # synchronized with remote main
            git fetch --all
            git reset --hard origin/main
            git clean -fd

            docker compose down --remove-orphans || true

            docker compose up -d --build --remove-orphans

            echo "Waiting for db container to become healthy..."

            TIMEOUT=120
            START=$(date +%s)
            while true; do
              DB_CID=$(docker compose ps -q db 2>/dev/null || true)
              if [ -n "$DB_CID" ]; then
                STATUS=$(docker inspect -f '{{.State.Health.Status}}' "$DB_CID" 2>/dev/null || true)
                if [ "$STATUS" = "healthy" ]; then
                  echo "db is healthy"
                  break
                fi
              fi
              NOW=$(date +%s)
              ELAPSED=$((NOW-START))
              if [ "$ELAPSED" -gt "$TIMEOUT" ]; then
                echo "Timed out waiting for db to become healthy (proceeding anyway)"
                break
              fi
              sleep 2
            done

            echo "Running migrations..."
            docker compose exec -T app python manage.py migrate --noinput

            echo "Collect static files..."
            docker compose exec -T app python manage.py collectstatic --noinput

            echo "Starting (or restarting) celery worker..."
            docker compose up -d --no-build celery_worker

            docker compose restart app || true

            echo "Deployment finished successfully"
