name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            set -e
            echo "🚀 Starting deployment..."
            
            cd ${{ secrets.DEPLOY_PATH }}
            
            # Pull latest changes
            echo "Pulling latest changes..."
            git fetch --all
            git reset --hard origin/main
            
            # Stop and remove existing containers
            echo "Stopping existing containers..."
            docker compose down || true
            
            # Build and start containers (WITHOUT minio profile)
            echo "Building and starting containers..."
            docker compose up -d --build
            
            # Wait for services to be ready
            echo "Waiting for services to be ready..."
            sleep 30
            
            # Run Django migrations
            echo "Running database migrations..."
            docker compose exec -T app python manage.py migrate
            
            # Collect static files
            echo "Collecting static files..."
            docker compose exec -T app python manage.py collectstatic --noinput
            
            # Restart Celery workers
            echo "Restarting Celery workers..."
            docker compose restart celery_worker
            
            # Health check
            echo "Performing health check..."
            curl -f http://localhost:8000/api/docs/ || echo "⚠️ API docs might not be accessible yet"
            
            echo "Deployment completed successfully!"